#!/bin/bash

: ${DEST_HOST:=example.com}
: ${DEST_PORT:=443}
: ${LOCAL_PORT:=443}
: ${MAX_CONN:=100}

## See http://linux.die.net/man/1/ncat for more on what these mean.

ncat -l -p $LOCAL_PORT -k -m $MAX_CONN --sh-exec "ncat $DEST_HOST $DEST_PORT"
